### ISSUE TITLE
Data, area and use-case

### ISSUE THREAD

**Issue by MarcelReuvers** [geo4web-testbed/general#1]
For discussion:

Hi All,

Below are the facts of the tender document. 

Topic 2
Area: Valkenswaard

Large scale topography (BGT)
Building and Addresses (BAG)
Land cover data, spatial plan (available as linked data)
OSM data

Topic 3
Area: Valkenswaard

Land cover data spatial plan (available as linked data)

Topic 4
Area: Valkenswaard

Large scale topography (BGT)
Farmland (AAN)

So what we did was already concentrated on 1 location. I don’t have problems when there are taken other area’s too but this helps in getting the different topics more aligned.

The main reason for Valkenswaard was that BGT data was already available and for the municipality we have land cover data (spatial plan) available with ‘intelligent’ text. Most of the spatial plans have pdf as 'text' documents. For Valkenswaard this is available as XML and we already translated this to linked data (see links in the tender document).

For the use case of the environmental law this could be one of the cases:

These environmental services provide customized information. That is information that focuses on the place, time and type of activity that the end user wants to develop. Not more and not less.

An initiator, private entrepreneur wants to expand its operations. He want to find a ‘good’ place for locating a ‘kinderdagverblijf’(childs place for parents that are working).

That is information that focuses on:
• the place, Valkenswaard (BGT data available)
• the time, January 2015
• the type of activity, kinderdagverblijf 

Using the spatial plan of Valkenswaard, complete with real-world cases. 

Data sources:
• spatial plans
• ‘kinderdagverblijf’, http://www.landelijkregisterkinderopvang.nl/pp/StartPagina.jsf 
• BGT for 'topo' objects (safety security, trees, no busy roads, playgrounds, etc)
• CBS data
o neighborhood composition (salary level, two-income households, etc.)
o companies> 100 employees in the area (potential customers)
o etc
• traffic accidents, http://spotzi.com/nl/kaarten/buurt/verkeer-en-vervoer/verkeersongevallen/ !!!
• Crimes, https://www.politie.nl/mijn-buurt/misdaad-in-kaart?geoquery=6642DJ&distance=5.0 
• etc

Items on the web
• IMRO
• IMGeo, definities.geostandaarden.nl

**Comment by cportele** [comment]
Hi Marcel, a small comment on topic 4: It is _BAG_ not _BGT_ in the tender document and we have been working mpstly with the available BAG WFS so far. Since topic 2 already covers BGT that should be ok as it is.

**Comment by joostfarla** [comment]
Sounds to me like a good use case!

> neighborhood composition (salary level, two-income households, etc.)

We've already imported the "gemeentes/wijken/buurten 2014" dataset with all these CBS stats. Next iteration we will offer this as linked data, so this could be used by the other teams.

Can we get the data from "Landelijk Register Kinderopvang en Peuterspeelzalen" as a raw dataset?

**Comment by lvdbrink** [comment]
Hi Joost, 

I think you can, it's at data.overheid.nl: 

https://data.overheid.nl/data/dataset/gegevens-kinderopvanglocaties-lrkp

**Comment by adbgnm** [comment]
Another interesting dataset for a safety use case would be this WFS Risk Map...
http://servicespub.risicokaart.nl/rk_services_pub/services/WFS-risicokaart.

It contains lots of layers with locations of vulnerable objects (among others schools, child's day care(?), and elderly homes), storage of explosives, road accidents information on roads/railways and so forth...

**Comment by joostfarla** [comment]
Awesome, thanx @adbgnm!

**Comment by ghost** [comment]
@joostfarla for the creation of Linked Data from any source it would be good to use existing vocabularies such as [core location](http://www.w3.org/ns/locn). (this is for the plain JSON-LD usecase, not schema.org indexing). This will guarantee semantic interoperability. I can help you with that if you need.

**Comment by joostfarla** [comment]
@liekeverhelst Great! I'll get in touch once we're starting with this!
