### ISSUE TITLE
Questions for the schema.org developers

### ISSUE THREAD

**Issue by ghost** [geo4web-testbed/general#2]
During this testbed we have ran into questions about the working of schema.org-RDF as demonstrated in [Google's structured data testing tool](https://developers.google.com/structured-data/testing-tool/).

The most important question is: when a piece of code fails validation, what happens with that source, will it be indexed or does the indexer skips it, or else?

Are there any Linked Data principles that schema.org does not (intend to) support? We notice that the structure data validator does not recognise certain Linked Data principles, such as multi-typing (a resource can have more than one rdf:type). Also the validator rejects links to any vocabulary other than schema.org. One would expect that this is tolerated with a warning that an inferencing engine will add triples.

**Comment by danbri** [comment]
the validator complains too much, but is harmless. Use the hierarchy viewer to see if the basic structure parsed OK. Can respond in more detail when I get back to UK. See http://googleresearch.blogspot.com/2015/12/four-years-of-schemaorg-recent-progress.html and the ACM article for notes on principles.

**Comment by ghost** [comment]
@danbri thanks for your comments. From the ACM article I understand that schema.org sets itself a little bit aside from Linked Data. Our concrete question is this: does it make sense/does it add any value to mingle other Linked Data in schema.org markup in HTML documents such as this example (which btw the validator rejects ):

```
{ "@context":"http://schema.org",
      "@id": "http://example.org/aan/place/1356489",
      "@type": "http://schema.org/Place",
      "description" :"my place",
      "http://www.w3.org/2002/07/owl#sameAs":
      [ {"@id":"http://anotherexample.org/xyz/place/12345", 
      "@type":  "http://schema.org/GeoShape"}],      
      "containedInPlace": [{"@type":"http://dbpedia.org/ontology/Place",
      "@id": "http://dbpedia.org/resource/Amsterdam"}]
}
```

**Comment by danbri** [comment]
I'm not sure about the specific JSON-LD structure here, but in general - mixing in other RDF vocabularies alongside schema.org is perfectly sensible. Whether it is useful depends on having some application in mind to consume the extra info. As far as I know non of the mainstream search engines say that they will do so, but it should be harmless at least. But you might also sometimes want to be consuming the data elsewhere e.g. local search tools, Web Components, or e.g. integration with analytics (for example http://www.swellpath.com/2015/03/7-steps-to-pushing-json-structured-data-using-google-tag-manager/ )....

**Comment by ghost** [comment]
@danbri thanks..all clear!
